FROM alpine:3.7
LABEL maintainer "Brad Rush <brad@fyvm.org>"

EXPOSE 80 443 2015

RUN apk add --no-cache ca-certificates curl

COPY artifacts/binaries/linux/amd64/caddy /bin/

ENTRYPOINT ["/bin/caddy"]
